---
apiVersion: v1
kind: Namespace
metadata:
  name: site-b-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-b-app
  namespace: site-b-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-b-app
  template:
    metadata:
      labels:
        app: site-b-app
    spec:
      containers:
        - name: nginx-site-b
          image: ghcr.io/vincepower/nginx-site-b:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: site-b-svc
  namespace: site-b-ns
spec:
  selector:
    app: site-b-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-b-ingress
  namespace: site-b-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /b
            pathType: Prefix
            backend:
              service:
                name: site-b-svc
                port:
                  number: 80
